twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']

    globals:
        cart_service: '@App\Service\CartService'

when@test:
    twig:
        strict_variables: true
